# Generated by Django 5.2.4 on 2025-08-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizHaqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_qator', models.CharField(max_length=70)),
                ('pastda_sarlovha', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('birinchi_katta_rasm', models.ImageField(upload_to='images')),
                ('ikkinchi_kichkina_rasm', models.ImageField(upload_to='images')),
                ('nech_yillik_tajriba', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ishxonanomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=30)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kirgandagitext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=70)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv_ichidagi_text', models.CharField(max_length=22)),
                ('kv_ichidagi_son', models.CharField(max_length=10)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=70)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ptchkalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptch', models.CharField(max_length=50)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tashhislar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashhislar_nomi', models.CharField(max_length=30)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaqtManzilTelefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_raqam', models.CharField(max_length=17)),
                ('haftani_qaysi_kuni_boshlash', models.CharField(max_length=9)),
                ('haftani_qaysi_kuni_yakunlash', models.CharField(max_length=9)),
                ('ish_boshlash_vaqti', models.CharField(max_length=5)),
                ('ishni_yakunlash_vaqti', models.CharField(max_length=5)),
                ('manzil', models.CharField(max_length=255)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_turi', models.CharField(max_length=25)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_qator', models.CharField(max_length=70)),
                ('video_ustodagi_soz', models.CharField(max_length=70)),
                ('videoni_ustidagi_rasm', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
                ('video_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.videoturi')),
            ],
        ),
        migrations.CreateModel(
            name='Xizmatlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_qator', models.CharField(max_length=70)),
                ('sarlovha', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=70)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
                ('qaysi_turdagi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.tashhislar')),
            ],
        ),
    ]
