# Generated by Django 5.2.4 on 2025-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_rasmi', models.ImageField(upload_to='images')),
                ('doctorni_instagrami_url', models.TextField()),
                ('doctorni_facebook_url', models.TextField()),
                ('doctorni_twitter_url', models.TextField()),
                ('doctorni_linkedin_url', models.TextField()),
                ('docotr_famila_ismi', models.CharField(max_length=30)),
                ('docotr_mutaxasisligi', models.CharField(max_length=30)),
                ('doctor_haqida_malumot', models.CharField(max_length=100)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
