# Generated by Django 5.2.4 on 2025-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_doctor_doctorni_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha_rasmi', models.ImageField(upload_to='images')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
