# Generated by Django 5.2.4 on 2025-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_galareya'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngKOpSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=50)),
                ('javob', models.TextField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
