# Generated by Django 5.2.4 on 2025-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_engkopsavol'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineQabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('info', models.TextField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
