# Generated by Django 5.2.4 on 2025-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_botniozgartirish_kanlaniozgartirish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bemorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=400)),
                ('yil', models.IntegerField()),
                ('hudud', models.CharField(max_length=100)),
                ('summa', models.IntegerField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('har_safar_ozgartirilgandagi_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
